// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: IdentityInfo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //	定义字段，赋值(=1) 是使用数字标识的编号。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *IdentityInfo) Reset() {
	*x = IdentityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IdentityInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityInfo) ProtoMessage() {}

func (x *IdentityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_IdentityInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityInfo.ProtoReflect.Descriptor instead.
func (*IdentityInfo) Descriptor() ([]byte, []int) {
	return file_IdentityInfo_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdentityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IdentityInfoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdentityInfoId) Reset() {
	*x = IdentityInfoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IdentityInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityInfoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityInfoId) ProtoMessage() {}

func (x *IdentityInfoId) ProtoReflect() protoreflect.Message {
	mi := &file_IdentityInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityInfoId.ProtoReflect.Descriptor instead.
func (*IdentityInfoId) Descriptor() ([]byte, []int) {
	return file_IdentityInfo_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityInfoId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_IdentityInfo_proto protoreflect.FileDescriptor

var file_IdentityInfo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x31, 0x22, 0x32,
	0x0a, 0x0c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x32, 0x97, 0x01, 0x0a, 0x13, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0f,
	0x61, 0x64, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x49,
	0x64, 0x12, 0x3b, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x1e,
	0x0a, 0x10, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x31, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x63, 0x6e, 0x5a, 0x0a, 0x2e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_IdentityInfo_proto_rawDescOnce sync.Once
	file_IdentityInfo_proto_rawDescData = file_IdentityInfo_proto_rawDesc
)

func file_IdentityInfo_proto_rawDescGZIP() []byte {
	file_IdentityInfo_proto_rawDescOnce.Do(func() {
		file_IdentityInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_IdentityInfo_proto_rawDescData)
	})
	return file_IdentityInfo_proto_rawDescData
}

var file_IdentityInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_IdentityInfo_proto_goTypes = []interface{}{
	(*IdentityInfo)(nil),   // 0: example1.IdentityInfo
	(*IdentityInfoId)(nil), // 1: example1.IdentityInfoId
}
var file_IdentityInfo_proto_depIdxs = []int32{
	0, // 0: example1.IdentityInfoService.addIdentityInfo:input_type -> example1.IdentityInfo
	1, // 1: example1.IdentityInfoService.getInfo:input_type -> example1.IdentityInfoId
	1, // 2: example1.IdentityInfoService.addIdentityInfo:output_type -> example1.IdentityInfoId
	0, // 3: example1.IdentityInfoService.getInfo:output_type -> example1.IdentityInfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IdentityInfo_proto_init() }
func file_IdentityInfo_proto_init() {
	if File_IdentityInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_IdentityInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IdentityInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityInfoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IdentityInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_IdentityInfo_proto_goTypes,
		DependencyIndexes: file_IdentityInfo_proto_depIdxs,
		MessageInfos:      file_IdentityInfo_proto_msgTypes,
	}.Build()
	File_IdentityInfo_proto = out.File
	file_IdentityInfo_proto_rawDesc = nil
	file_IdentityInfo_proto_goTypes = nil
	file_IdentityInfo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentityInfoServiceClient is the client API for IdentityInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityInfoServiceClient interface {
	AddIdentityInfo(ctx context.Context, in *IdentityInfo, opts ...grpc.CallOption) (*IdentityInfoId, error)
	GetInfo(ctx context.Context, in *IdentityInfoId, opts ...grpc.CallOption) (*IdentityInfo, error)
}

type identityInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityInfoServiceClient(cc grpc.ClientConnInterface) IdentityInfoServiceClient {
	return &identityInfoServiceClient{cc}
}

func (c *identityInfoServiceClient) AddIdentityInfo(ctx context.Context, in *IdentityInfo, opts ...grpc.CallOption) (*IdentityInfoId, error) {
	out := new(IdentityInfoId)
	err := c.cc.Invoke(ctx, "/example1.IdentityInfoService/addIdentityInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityInfoServiceClient) GetInfo(ctx context.Context, in *IdentityInfoId, opts ...grpc.CallOption) (*IdentityInfo, error) {
	out := new(IdentityInfo)
	err := c.cc.Invoke(ctx, "/example1.IdentityInfoService/getInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityInfoServiceServer is the server API for IdentityInfoService service.
type IdentityInfoServiceServer interface {
	AddIdentityInfo(context.Context, *IdentityInfo) (*IdentityInfoId, error)
	GetInfo(context.Context, *IdentityInfoId) (*IdentityInfo, error)
}

// UnimplementedIdentityInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityInfoServiceServer struct {
}

func (*UnimplementedIdentityInfoServiceServer) AddIdentityInfo(context.Context, *IdentityInfo) (*IdentityInfoId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIdentityInfo not implemented")
}
func (*UnimplementedIdentityInfoServiceServer) GetInfo(context.Context, *IdentityInfoId) (*IdentityInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}

func RegisterIdentityInfoServiceServer(s *grpc.Server, srv IdentityInfoServiceServer) {
	s.RegisterService(&_IdentityInfoService_serviceDesc, srv)
}

func _IdentityInfoService_AddIdentityInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInfoServiceServer).AddIdentityInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example1.IdentityInfoService/AddIdentityInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInfoServiceServer).AddIdentityInfo(ctx, req.(*IdentityInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityInfoService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityInfoId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInfoServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example1.IdentityInfoService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInfoServiceServer).GetInfo(ctx, req.(*IdentityInfoId))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example1.IdentityInfoService",
	HandlerType: (*IdentityInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addIdentityInfo",
			Handler:    _IdentityInfoService_AddIdentityInfo_Handler,
		},
		{
			MethodName: "getInfo",
			Handler:    _IdentityInfoService_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "IdentityInfo.proto",
}
